server:
  name: "project-api"
  addr: "127.0.0.1:80"

zap:
  debugFileName: "C:\\goCode\\ms_project\\logs\\debug\\project-debug.log"
  infoFileName: "C:\\goCode\\ms_project\\logs\\info\\project-info.log"
  warnFileName: "C:\\goCode\\ms_project\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"