server:
  name: "project-user"
  addr: "0.0.0.0:8080"

zap:
  debugFileName: "/logs/debug/project-debug.log"
  infoFileName: "/logs/info/project-info.log"
  warnFileName: "/logs/error/project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "redis6"
  port: 6379
  password: "123456"
  db: 1
grpc:
  name: "user"
  addr: "0.0.0.0:8881"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd3:2379"
mysql:
  username: root
  password: "123456"
  host: host.docker.internal
  port: 3309
  db: msproject