basePath: 这里写base path
host: 这里写接口服务的host
info:
  contact:
    email: support@swagger.io
    name: 这里写联系人信息
    url: http://www.swagger.io/support
  description: 这里写描述信息
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 这里写标题
  version: "1.0"
paths:
  /project/index:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 升级版帖子列表接口
      tags:
      - 帖子相关接口
swagger: "2.0"
